version: '3.8'
services:
  web:
    build:
      context: .
      args:
        NODE_ENV: production
        NEXT_PUBLIC_BASE_URL: 'http://localhost:8181/'
    ports:
      - "3000:3000"
    environment:
      # NODE_ENV: production
      NODE_ENV: production
